language: android
android:
  components:
    - android-26
    - build-tools-26.0.2
    - extra-google-m2repository
    - extra-android-support
    - extra-android-m2repository

script: ./gradlew assemble test check