language: android
android:
  components:
    - android-29
    - build-tools-29.0.0
    - extra-google-m2repository
    - extra-android-support
    - extra-android-m2repository

script: ./gradlew assemble test check
